### ISSUE TITLE
Proposal: Combine ETH & BSC branch into one?

### ISSUE THREAD

**Issue by Phineas** [waifusion/waifusion-site#64]
Seeing as the ETH and BSC version of the Waifusion site is so similar, it might be a good idea to combine them into the same branch, then check the current URL the user's on (e.g. either waifusion.sexy or waifusionbsc.sexy) and adjust the RPC URL, dungeon contract address and a couple other things based on that. We could also have a global variable override for development purposes.

This would make the development workflow a lot easier as we wouldn't have to keep merging master into the bsc branch and it would generally unify the codebase.

**Comment by chase-manning** [comment]
@Phineas  Great idea!!! <3
